language: cpp
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - cmake
      - gcc-avr
      - avr-libc

compiler:
  - gcc

script:
  - avr-gcc --version
  - mkdir -p bld
  - cd bld
  - cmake ..
  - make
  - make test
